# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins:
  - jekyll-paginate
  - jemoji
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://akronix.github.io/
baseurl: ""
title: Akronix's website
author: Abel Serrano Juste
description: Personal blog and resume
avatar: profile.png
email: akronix5@gmail.com
github: akronix # username
twitter: Akronix5
stackoverflow: users/2904315/akronix   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
