# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-feed
port: 3000
safe: true


# Web parameters
url: https://abeserra.me
baseurl: ""
title: Abel's website
author: Abel Serrano Juste
description: Home of Abel 'Akronix' Serrano Juste. Website and blog.
avatar: profile.jpg
email: akronix5@gmail.com

# social
github: akronix # username
twitter: Akronix5
mastodon:
  user: Akronix
  server: mastodon.librelabucm.org
stackoverflow: users/2904315/akronix   #e.g: users/2735833/proton1h1
rss: true

# other
gpguid: 04D567B93E6702F7
gpglink: http://pgp.librelabucm.org/pks/lookup?op=get&search=0x04D567B93E6702F7

#Comment out if you don't want disqus
disqus: akronix
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
